[project]
name = "time-zone-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "st-autorefresh>=0.1.0",
    "streamlit>=1.43.1",
    "tzdata>=2025.1",
]
